services:
  bot:
    build: .
    container_name: my-telegram-bot
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://botuser:botpass@db:5432/botdb

  db:
    image: postgres:16
    container_name: bot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: botdb
      POSTGRES_USER: botuser
      POSTGRES_PASSWORD: botpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    build: ./admin  # Контекст: /root/py-bot/admin/, Dockerfile там
    container_name: bot-admin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"  # Хост:8080 -> контейнер:8080 (/code/ uvicorn)
    environment:
      - DB_URL=postgresql://botuser:botpass@db:5432/botdb  # Используется в /code/models.py

volumes:
  postgres_data: